services:
  portfolio:
    build:
      context: .
      dockerfile: build/ci/Dockerfile
    working_dir: /app/src
    volumes:
      - ./src:/app/src
    environment:
      - APP_ENV=testing
      - DB_CONNECTION=sqlite
      - "DB_DATABASE=:memory:"
      - CACHE_DRIVER=array
      - CACHE_STORE=array
      - SESSION_DRIVER=array
      - QUEUE_CONNECTION=sync
