sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        send_default_pii: true
        ignore_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
